apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  storage:
    size: 1Gi

  replicas: 3
  
  # point to an existing MaxScale instance. Doing this will delegate tasks such as primary failover to MaxScale.
  # maxScaleRef:
  #   name: maxscale-galera

  # provision a MaxScale instance and set 'spec.maxScaleRef' automatically.
  maxScale:
    enabled: true
    
    kubernetesService:
      type: LoadBalancer

    guiKubernetesService:
      type: LoadBalancer

    connection:
      secretName: mxs-galera-conn
      port: 3306

    metrics:
      enabled: true

  galera:
    enabled: true

  metrics:
    enabled: true
